### ISSUE TITLE
Fail to create volume with your exemple

### ISSUE THREAD

**Issue by maxlerebourg** [thatsk/nfs-csi#1]
Hello @thatsk, thanks to write this repository, you save me a lot of time !

I follow all your configuration file, and adapt it to my setup. BUT, at the volume creation, I get :

```
Error creating volume: Unexpected response code: 500 (1 error occurred:
        * controller create volume: rpc error: controller create volume: CSI.ControllerCreateVolume: volume "answer" snapshot source &{"" ""} is not compatible with these parameters: rpc error: code = InvalidArgument desc = server is a required parameter)
```
To make it work, I change `context` to `parameters` and that's it.
I don't know if you still use this configuration, but for newcomers it can be a great help.

**Comment by thatsk** [comment]
what command you are running

**Comment by thatsk** [comment]
it will not create as its nfs read-only you need to use register command so it will look like below:-
```
nomad volume register volume.nomad
```

**Comment by thatsk** [comment]
i updated README.md

**Comment by maxlerebourg** [comment]
I used `nomad volume create nfs-vol.hcl`.
And with what i did, I was able to create this volume :)

**Comment by maxlerebourg** [comment]
Additionnal comment: Idk if it is the case with this csi plugin but it may require to have the package `nfs-common` on the Nomad client Host. So it can be helpful on Readme.

**Comment by thatsk** [comment]
https://github.com/thatsk/nfs-csi/blob/main/nfs-plugin-nodes.nomad
i don't think so this plugin nodes system job take care of it.

**Comment by thatsk** [comment]
so when you are creating nfs-vol does it actually create nfs volume on the nfs side? If yes please share example with nfs server config or which nfs server you are using so that we can evaluate.

**Comment by maxlerebourg** [comment]
server nfs :
```sh
cat /etc/exports
/mnt/nfs4 *(rw,sync,no_root_squash,no_subtree_check)
chmod 777 -R /mnt/nfs4
ls /mnt/nfs4
no_file
```
In addition to your exemple file, i added for controller and nodes because I don't use Consul
```
...
group "nodes" {
    service  {
      provider = "nomad"
    }
...
```
nfs4-volume.hcl :
```
type = "csi"
id = "answer"
name = "answer"
plugin_id = "nfsofficial"
external_id = "testid"
capability {
  access_mode = "multi-node-multi-writer"
  attachment_mode = "file-system"
}
parameters {
  server = "$IP_NFS_SERVER"
  share = "/mnt/nfs4"
  mountPermissions = "0"
}
mount_options {
  fs_type = "nfs"
  mount_flags = [ "timeo=30", "intr", "vers=4", "_netdev" , "nolock" ]
}
```
I did `nomad volume create nfs4-volume.hcl` and it's worked, it runs since this morning on my nomad without bugs and I move a service to another node, and.... it works !

On the nfs server :
```
ls /mnt/nfs4
anwser (as directory)
```

**Comment by thatsk** [comment]
Oh I thought it's different nfs server with some authentication and you are trying to add nfs authentication in that .but we can also try to see add authentication around it nomad volume create will work if it's open nfs server but bug storage system will not provide it open system so we need to use register as they just export the nfs mount point

**Comment by thatsk** [comment]
Feel free to raise pr if you found anything missing

**Comment by thatsk** [comment]
Closing this now
