### ISSUE TITLE
Cannot use volume created

### ISSUE THREAD

**Issue by alfkonee** [thatsk/nfs-csi#2]
I get this Error in the pre-hook phase
`failed to setup alloc: pre-run hook "csi_hook" failed: rpc error: code = InvalidArgument desc = server is a required parameter`
![image](https://user-images.githubusercontent.com/3909521/230218293-45347fa5-daf3-43e9-9a70-f358f6e9942a.png)

here is my volume definitions
```hcl
type = "csi"
id = "test"
name = "test"
plugin_id = "nfsofficial"
external_id = "testid"
capability {
	access_mode = "multi-node-multi-writer"
	attachment_mode = "file-system"
}
parameters {
  server = "$IP_OF_HOST"
  share = "/storage/nfs/try"
  mountPermissions = "0"  
}
mount_options {
  fs_type = "nfs"
  mount_flags = [ "timeo=30", "intr", "vers=4", "_netdev" , "nolock" ]
}
```

is there something I might be missing??

**Comment by matthiasschoger** [comment]
Use a "context" stanza instead of "parameter"

**Comment by thatsk** [comment]
@alfkonee  pls update context i am closing this feel free to open
